name: c_m_s_report_labortary
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  cached_network_image: ^3.4.1
  animated_custom_dropdown: ^3.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - "assets/"
    - "assets/bg_images/"
    - "assets/logo/"
     


